### ISSUE TITLE
need to redirect to the correct forms

### ISSUE THREAD

**Issue by achevalet** [achevalet/foreman_openstack_v3#1]
app/views/compute_resources/form/_openstack.html.erb built-in is used instead of the one provided, workaround is to rename the built-in form

**Comment by timogoebel** [comment]
@achevalet, you could try something like this. I haven't tested if this actually works, so this is just a suggestion.
[prepend_view_path](http://apidock.com/rails/ActionView/ViewPaths/prepend_view_path) might be worth trying, too.

in `lib/foreman_openstack_v3/engine.rb`
```ruby
config.after_initialize do
      engine_root = ForemanOpenstackV3::Engine.root.to_s
      prepended_view_path = engine_root + '/app/views'
      ActionController::Base.view_paths.unshift(prepended_view_path)
    end
```

**Comment by achevalet** [comment]
@timogoebel thank you so much, it works like a charm ! ;-)
